/* Generated by cutconv
 * Date: 2022-03-06 11:08:31 */

#define CUT
#define CUT_MAIN
#include "cut.h"

/* Regular ‹main()› function wrapper. */
#define main _test_main

/* Do «NOT» ever include ‹.c› files in production code!
 * It is a dirty hack to allow us to call your ‹main()›
 * from tests. It should «never» be used otherwise. */

#include "main.c"
#undef main

/* Canonical-Name: nanecisto_1
 * Description: Vstup ze zadání: Žádný příkaz */
TEST(nanecisto_1)
{
    INPUT_STRING(
            "; na vstupu se nenachazi zadny prikaz, komentar tedy nevyvola zadny vypis\n"
            "=\n");
    int status = _test_main();

    ASSERT((status) == 0);
    ASSERT_FILE(stdout,
            "# 0\n");
} /* nanecisto_1 */

/* Canonical-Name: nanecisto_2
 * Description: Vstup ze zadání: Jednoduchý výpis */
TEST(nanecisto_2)
{
    INPUT_STRING(
            "P\n"
            "10\n"
            "\n"
            "43\n");
    int status = _test_main();

    ASSERT((status) == 0);
    ASSERT_FILE(stdout,
            "# 1043\n");
} /* nanecisto_2 */

/* Canonical-Name: nanecisto_binary
 * Description: Binární vstup */
TEST(nanecisto_binary)
{
    INPUT_STRING(
            "P T 110\n"
            "=\n");
    int status = _test_main();

    ASSERT((status) == 0);
    ASSERT_FILE(stdout,
            "# 0\n"
            "# 6\n"
            "# 6\n");
} /* nanecisto_binary */

/* Canonical-Name: nanecisto_minus
 * Description: Odčítání */
TEST(nanecisto_minus)
{
    INPUT_STRING(
            "P 100\n"
            "- 50\n"
            "=\n");
    int status = _test_main();

    ASSERT((status) == 0);
    ASSERT_FILE(stdout,
            "# 100\n"
            "# 50\n"
            "# 50\n");
} /* nanecisto_minus */

/* Canonical-Name: nanecisto_octal
 * Description: Osmičkový vstup */
TEST(nanecisto_octal)
{
    INPUT_STRING(
            "P O 72\n"
            "=\n"
            "O\n");
    int status = _test_main();

    ASSERT((status) == 0);
    ASSERT_FILE(stdout,
            "# 0\n"
            "# 58\n"
            "# 58\n"
            "# 72\n");
} /* nanecisto_octal */

/* Canonical-Name: nanecisto_zadani::3
 * Description: Ukázka 3 */
TEST(nanecisto_zadani__3)
{
    INPUT_STRING(
            "P 21\n"
            "; okamzite provedeni prikazu vyse - ukonceni predchoziho vstupu\n"
            "\n"
            "P 22\n"
            "=\n"
            "\n"
            "; jednotlive prikazy nemusi byt oddeleny novym radkem\n"
            "P 23 =\n"
            "\n"
            "N\n");
    int status = _test_main();

    ASSERT((status) == 0);
    ASSERT_FILE(stdout,
            "# 21\n"
            "# 22\n"
            "# 22\n"
            "# 23\n"
            "# 23\n"
            "# 0\n");
} /* nanecisto_zadani::3 */

/* Canonical-Name: nanecisto_zadani::4
 * Description: Ukázka 4 */
TEST(nanecisto_zadani__4)
{
    INPUT_STRING(
            "P 200 ;\n"
            "/ 5 ;\n"
            "% 6 ;\n"
            "=\n");
    int status = _test_main();

    ASSERT((status) == 0);
    ASSERT_FILE(stdout,
            "# 200\n"
            "# 40\n"
            "# 4\n"
            "# 4\n");
} /* nanecisto_zadani::4 */

/* Canonical-Name: nanecisto_zadani::5
 * Description: Ukázka 5 */
TEST(nanecisto_zadani__5)
{
    INPUT_STRING(
            "P 10 ;\n"
            "< 3 ;\n");
    int status = _test_main();

    ASSERT((status) == 0);
    ASSERT_FILE(stdout,
            "# 10\n"
            "# 80\n");
} /* nanecisto_zadani::5 */

/* Canonical-Name: nanecisto_zadani::7
 * Description: Ukázka 7 */
TEST(nanecisto_zadani__7)
{
    INPUT_STRING(
            "P 15 ;\n"
            "* X 1a ;\n"
            "O ;\n");
    int status = _test_main();

    ASSERT((status) == 0);
    ASSERT_FILE(stdout,
            "# 15\n"
            "# F\n"
            "# 390\n"
            "# 606\n");
} /* nanecisto_zadani::7 */

/* Canonical-Name: nanecisto_zadani::8
 * Description: Ukázka 8 */
TEST(nanecisto_zadani__8)
{
    INPUT_STRING(
            "P 3 ;    akumulator = 3, pamet = 0\n"
            "M   ;    akumulator = 3, pamet = 3\n"
            "R   ;    akumulator = 3, pamet = 0\n"
            "M   ;    akumulator = 3, pamet = 3\n"
            "+ m ;    akumulator = 3 + 3 = 6, pamet = 3\n"
            "=\n");
    int status = _test_main();

    ASSERT((status) == 0);
    ASSERT_FILE(stdout,
            "# 3\n"
            "# 6\n"
            "# 6\n");
} /* nanecisto_zadani::8 */

/* Canonical-Name: nanecisto_zadani_6
 * Description: Vstupy ze zadání: Ukázka 6 */
TEST(nanecisto_zadani_6)
{
    INPUT_STRING(
            "P 21 + 43 * 5 =\n");
    int status = _test_main();

    ASSERT((status) == 0);
    ASSERT_FILE(stdout,
            "# 21\n"
            "# 64\n"
            "# 320\n"
            "# 320\n");
} /* nanecisto_zadani_6 */

/* End of generated tests. */
